### ISSUE TITLE
Running `index.py` fails with `Failed to connect to browser`

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/youtube-trusted-session-generator#14]
Interestingly, while the first time I ran it (in the course of solving https://github.com/iv-org/invidious/issues/4947), the script ran successfully, when I tried to re-run it today, at the same commit, package versions, Python version, and chromium version (`129.0.6668.58-1`), I get the error message
```
Exception:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Exception ignored in atexit callback: <function deconstruct_browser at 0xffffb8ecda80>
Traceback (most recent call last):
  File "/home/system/youtube-trusted-session-generator/venv/nodriver/core/util.py", line 124, in deconstruct_browser
    _.stop()
  File "/home/system/youtube-trusted-session-generator/venv/nodriver/core/browser.py", line 545, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'aclose'
```

The Chromium browser does open though.

**Comment by DUOLabs333** [comment]
Your patch that you mentioned [here](https://github.com/iv-org/youtube-trusted-session-generator/issues/3#issuecomment-2241694502) fixed the issue for me.

**Comment by hashamyounis9** [comment]
Hey @DUOLabs333!
hope you are doing well.
Can you please help me resolve this issue?

**Comment by DUOLabs333** [comment]
If you are using the official Docker Image, you should already have the patch (it was committed in July). However, if you're running the tool locally (like I am), then you should open `nodriver/core/browser.py` (located in the relevant site-packages), and change `await self.sleep(0.5)` to `await self.sleep(2)`.

**Comment by hashamyounis9** [comment]
Thank you so much @DUOLabs333 for this information. Really appreciate it.
Can you provide the link to official Docker image, couldn't find it on the docker hub.

**Comment by DUOLabs333** [comment]
The instructions are in the README.md.

**Comment by unixfox** [comment]
hello, I'm going to lock this github issue since the issue has been solved on docker for ages. The tutorial is located at https://docs.invidious.io/installation/#docker
