### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'closed'

### ISSUE THREAD

**Issue by vladimirdulov** [iv-org/youtube-trusted-session-generator#15]
Hello,

I've tried to build an image from the source and it seems building well, but it fails at runtime:

```
$ docker build . -t youtube-trusted-session-generator
```
Everything went just fine.

The error it fails with:
```
$ docker run youtube-trusted-session-generator 
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
Traceback (most recent call last):
  File "/usr/app/src/index.py", line 37, in <module>
    loop().run_until_complete(main())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/app/src/index.py", line 8, in main
    browser = await start(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 385, in start
    await self.connection.send(cdp.target.set_discover_targets(discover=True))
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/connection.py", line 396, in send
    if not self.websocket or self.closed:
                             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/connection.py", line 352, in __getattr__
    return getattr(self.target, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'closed'
successfully removed temp profile /tmp/uc_ih_f346b
```

**Comment by JackobStuard** [comment]
I have same issue

**Comment by gsuberland** [comment]
I had the same issue. As a workaround you can pull these tokens manually for now by opening a Chrome Incognito tab, hitting F12, going to the Network tab, ticking "Disable cache", typing `youtubei/v1/player` in the filter box, opening a YouTube video embed URL (`youtube.com/embed/[videoid]`), clicking the request that appears, selecting the Payload tab, then grabbing the `serviceIntegrityDimensions.poToken` and `context.client.visitorData` values manually from the JSON.

That said I'm still getting 403s for now, so no idea if pulling them manually is even doing anything for the moment.

**Comment by unixfox** [comment]
this is not related to this issue @gsuberland. please stay on topic.

**Comment by gsuberland** [comment]
@unixfox Apologies. Still, is it worth documenting that manual approach somewhere in the meantime, to help folks get the tokens if they can't get the session generator working?

**Comment by afeuerstein** [comment]
Downgrading websockets to 13.1 fixed this for me:
```
pip install websockets==13.1
```
Seems that this has been tracked and fixed somewhere upstream: https://github.com/seleniumbase/SeleniumBase/issues/3251

**Comment by unixfox** [comment]
Thank you @afeuerstein 

----------

@gsuberland Feel free to give this advice on matrix or create a new documentation page for alternatives to "youtube-trusted-session-generator". But don't talk about off-topic stuff thank you.

I do understand the idea of sharing advices, that's great but often this starts a whole new off-topic discussion where the main subject is then completely miss out.
