### ISSUE TITLE
Add support for Docker image platform linux/arm/v7

### ISSUE THREAD

**Issue by sagansfault** [iv-org/youtube-trusted-session-generator#16]
Currently the supported versions are amd64 and arm64. I cant run the image on my raspberry pi because it is armv7 architecture. Could support be added for this architecture?

**Comment by unixfox** [comment]
Rasperry pi do support ARM64 if you install an OS with this architecture.

We can add armv7 but I fail to understand how is it going to help you since invidious is ARM64 only.

(ARM64 = ARMv8)

**Comment by sagansfault** [comment]
Unfortunately I run Rasbian, I could switch to another OS, which I am considering.
As for why, I dont use invidious, this is for another project inwhich the webserver is very useful.

**Comment by unixfox** [comment]
Raspbian has ARM64 or also called 64-bit instructions image: https://www.raspberrypi.com/software/operating-systems/

**Comment by sagansfault** [comment]
I suppose it is time to upgrade. Thanks, closed.
