### ISSUE TITLE
make a pterodactyl egg for it.

### ISSUE THREAD

**Issue by itsjustnickdev** [iv-org/youtube-trusted-session-generator#17]

**Comment by unixfox** [comment]
I'm sorry we do not have time for that. We only support docker and non docker usage.

**Comment by CelluloidRacer2** [comment]
@itsjustnickdev you could probably figure out how to do this pretty easily using the Pterodactyl documentation for creating custom eggs and leveraging the existing youtube-trusted-session-generator Docker image on Quay (`quay.io/invidious/youtube-trusted-session-generator:webserver`)

For reference:
https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html
https://quay.io/repository/invidious/youtube-trusted-session-generator?tab=tags
