### ISSUE TITLE
[WARNING] update failed: unable to locate video player on the page

### ISSUE THREAD

**Issue by ChaseS-Dev** [iv-org/youtube-trusted-session-generator#24]
![image](https://github.com/user-attachments/assets/0591600f-113e-4ec9-80df-534a65e73460)

Any reason as to why it would fail to find the video player? The server is running Ubuntu 24.10 x64 with 512mb of ram if that matters.

**Comment by unixfox** [comment]
512Mb is too little ram for the full browser to run. You need at the very minimum 1GB.
