### ISSUE TITLE
How to run docker or without docker in chrome (I'm a noob)

### ISSUE THREAD

**Issue by ghost** [iv-org/youtube-trusted-session-generator#27]
I need to get potoken and visitor token.

I have never done this so I'm a noob, do I need a computer to do this or is this something that I can do with termux?

Is there a video tutorial?

**Comment by unixfox** [comment]
It's in the readme

**Comment by ghost** [comment]
> It's in the readme

I don't understand a single thing about it, I saw it but didn't understand a thing.

**Comment by MasterKia** [comment]
Is it too hard to use a search engine?
