### ISSUE TITLE
Check for po_token length size for workability or not

### ISSUE THREAD

**Issue by alexmaras** [iv-org/youtube-trusted-session-generator#7]
I originally posted this as a bug on the invidious issue tracker.

https://github.com/iv-org/invidious/issues/4884

When generating a po_token using the `quay.io/invidious/youtube-trusted-session-generator` image, I had playback issues with DASH, getting 403 errors whenever I tried to play back. There were some exceptions for short videos, but the majority just failed. All the details are over there too.

I tried generating fresh tokens today in case it was some kind of rate limit. I generated two tokens on two different machines with different outgoing IPs, and noticed that the token generated on my computer that _isn't_ on the same outgoing IP as invidious was twice as long as the po_token from the invidious machine.

The tokens I had generated before that point were 80 chars long, the new one is 160 characters. I then tried to generate some more on the machine that generated the 160 character token and got 80 character tokens again.

This could be a useful distinguishing factor as to whether the po token is going to work, though I'm not sure if others generally get the longer version.

**Comment by BenediktG-code** [comment]
@unixfox: I just discovered, that I needed to disable my pihole during the token generation with youtube-trusted-session-generator. 
The tokens I received with active pihole were 1437 characters long and did not work.
So maybe it's worth mentioning this in the documentation and checking for over-length [here](https://github.com/iv-org/youtube-trusted-session-generator/blob/master/index.py#L30)
